# Generated by Django 4.1.5 on 2023-01-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='hello_test_field',
            field=models.TextField(blank=True),
        ),
    ]
