name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd home-outer
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test home.apps.api 
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PIPELINE_POC_GHA_SECRET }}
        repository: ${{ github.repository }}
        event-type: Pylint
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
